
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Loterie</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" media="screen" href="css/main.css" />
    <script src="main.js"></script>
</head>
<body>
    <main>
        <h1>Les résultats de la loterie sont:</h1>
        <ul>

            <li><p><?= $loterie[0]; ?></p></li>
            <li><p><?= $loterie[1]; ?></p></li>
            <li><p><?= $loterie[2]; ?></p></li>
            <li><p><?= $loterie[3]; ?></p></li>
            <li><p><?= $loterie[4]; ?></p></li>
            <li><p><?= $loterie[5]; ?></p></li>
            
        </ul>
    </main>

</body>
</html>